name: Angular_and_Cypress_Tests

on:
  push:
    branches:
      - dev  # Modifier cette branche si nécessaire
  pull_request:
    branches:
      - dev  # Modifier cette branche si nécessaire

jobs:
  angular_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

    - name: Run unit tests
      run: npm test
      continue-on-error: true

    - name: Run end-to-end tests with Cypress
      run: npm run cy:run
      continue-on-error: true

    - name: Send notification if tests fail
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'CI Test Failure Notification'
        to: 'recipient@example.com'
        from: 'CI Bot <your-email@example.com>'
        body: |
          Hello,

          This is an automated message to inform you that the CI tests have failed.

          Please check the build logs for more details.

          Regards,
          Your CI Bot
