name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm start
      # Attendre que le serveur soit prêt
      # Peut-être utiliser un script personnalisé pour vérifier si le serveur est prêt

    - name: Run end-to-end tests with Cypress
      run: npm run cy:run
