name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start server
      run: |
        npm start &
        until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
            echo "Waiting for server to start..."
            sleep 1
        done
        echo "Server started successfully."

    - name: Run end-to-end tests with Cypress
      run: |
        npm run cy:run
        if [ $? -eq 0 ]; then
          echo "All tests passed successfully."
        else
          echo "Some tests failed. Check the logs for details."
          exit 1
        fi
