name: Angular_and_Cypress_Tests

on:
  push:
    branches:
      - dev  # Modifier cette branche si nécessaire
  pull_request:
    branches:
      - dev  # Modifier cette branche si nécessaire

jobs:
  angular_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Run Angular tests
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Run Angular Server
        run: ng serve

      - name: Run Cypress tests
        run: npm run cypress:run
