name: Angular_and_Cypress_Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  angular_and_cypress_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Run Angular tests
        id: angular-tests
        run: ng test --watch=false --browsers=ChromeHeadless
        continue-on-error: true

      - name: Generate Angular test report
        run: npm run generate-angular-report

      - name: Upload Angular test report
        uses: actions/upload-artifact@v3
        with:
          name: angular-report
          path: output/report

      - name: Build Angular application
        run: ng build

      - name: Run Cypress tests
        id: cypress-tests
        run: npm run cypress:run
        continue-on-error: true

      - name: Generate Cypress HTML report
        run: npm run cypress:report

      - name: Upload Cypress test report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: output/report
