name: Angular_and_Cypress_Tests

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  angular_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Run Angular tests
        id: angular-tests
        run: ng test --watch=false --browsers=ChromeHeadless
        continue-on-error: true

      - name: Run Cypress tests and ng serve
        id: cypress-tests
        run: |
          ng serve --open &
          while ! nc -z localhost 4200; do sleep 1; done
          npm run cy:run
        continue-on-error: true

      - name: Set failure status
        if: ${{ steps.angular-tests.outcome == 'failure' || steps.cypress-tests.outcome == 'failure' }}
        run: echo "One or more tests have failed."

      - name: Send notification if tests fail
        if: ${{ steps.angular-tests.outcome == 'failure' || steps.cypress-tests.outcome == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'CI Test Failure Notification'
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}  
          body: |
            Bonjour,
            Message automatique pour vous informez que les test CI ont échoué.
            Regarder les logs pour plus de détails.
            Aller bisous,
            Ton robot CI 
