name: Angular_and_Cypress_Tests

on:
  push:
    branches:
      - dev  # Modifier cette branche si nécessaire
  pull_request:
    branches:
      - dev  # Modifier cette branche si nécessaire

jobs:
  angular_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

    - name: Run unit tests
      run: npm test
      continue-on-error: true

    - name: Run end-to-end tests with Cypress
      run: npm run cy:run
      continue-on-error: true

    - name: Publish test results as artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          ./path/to/unit/test/results
          ./path/to/cypress/test/results
